name: fazkorony
description:

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # ===== موجودة لديك =====
  shared_preferences: ^2.2.2
  cupertino_icons: ^1.0.2
  hijri: ^3.0.0
  audioplayers: ^6.5.0
  uuid: ^4.2.1
  path: ^1.8.3
  intl: ^0.20.2
  share_plus: ^12.0.1

  # ===== Firebase (متوافقة مع firebase_core ^4) =====
  firebase_core: ^4.0.0
  firebase_storage: ^13.0.3
  firebase_auth: ^6.0.1
  firebase_messaging: ^16.0.0

  string_validator: ^1.0.2
  easy_container: ^1.0.4
  sensors_plus: ^7.0.0
  pdfx: ^2.6.0
  flutter_screenutil: ^5.9.3
  http: ^1.2.0
  shimmer: ^3.0.0
  timezone: ^0.10.1
  adhan: ^2.0.0
  flutter_local_notifications: ^19.4.2
  provider: ^6.1.5+1
  path_provider: ^2.1.4
  android_intent_plus: ^6.0.0
  permission_handler: ^12.0.1
  flutter_timezone: ^5.0.0
  cached_network_image: ^3.3.0
  file_picker: ^10.3.3
  connectivity_plus: ^7.0.0
  url_launcher: ^6.1.11
  webview_flutter: ^4.7.0
  archive: ^4.0.7
  flutter_animate: ^4.5.0
  sqflite: ^2.3.0
  dio: ^5.9.0
  fluttericon: ^2.0.0
  fluttertoast: ^9.0.0
  iconsax: ^0.0.8
  scrollable_positioned_list: ^0.3.8
  superellipse_shape: ^0.2.0
  flutter_keyboard_visibility: ^6.0.0
  group_list_view: ^1.1.1
  
  # =flutter_qiblah==== قسم القبلة =====
  flutter_svg: ^2.2.1
  lottie: ^3.0.0

  
  # ===== قسم القرآن: الحزمة المحلية =====
  quran:
    path: modules/quran

  # ===== واجهات وتنسيقات =====
  modal_bottom_sheet: ^3.0.0
  flutter_colorpicker: ^1.1.0
  # Use flutter_compass_v2 (flutter_qiblah depends on it). Remove the old
  # flutter_compass package to avoid duplicate native plugin classes.
  flutter_compass_v2: ^1.0.3
  flutter_html: ^3.0.0
  screenshot: ^3.0.0
  image_gallery_saver_plus: ^4.0.1


  # ===== الصوت + إدارة الحالة =====
  just_audio: ^0.10.5
  just_audio_background: ^0.0.1-beta.17
  audio_session: ^0.2.2
  flutter_bloc: ^9.0.0
  equatable: ^2.0.7
  ffmpeg_kit_flutter_new: ^4.0.0
  visibility_detector: any
  wakelock_plus: ^1.4.0
  arabic_roman_conv: any
  audio_meta: any
  syncfusion_flutter_sliders: any

  # ===== التخزين المحلي =====
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  geolocator: ^13.0.4
  flutter_qiblah: ^3.1.0+1
  bloc: ^9.1.0
  meta: ^1.16.0

dependency_overrides:
  # Android-specific override only
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  image: ^4.2.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/html/
    - assets/raw/
    - assets/countries+states+cities.json
    - assets/13624650881.pdf
    # ===== بيانات وأصول القرآن =====
    - assets/quran/json/surahs.json
    - assets/quran/json/quarters.json
    - assets/quran/images/
    - assets/quran/fonts/
    - assets/mushaf_layout/
    - assets/mushaf_pages/

  fonts:
    - family: QPCV1
      fonts:
        - asset: assets/mushaf_layout/QPC V1 Font.ttf
        - asset: assets/mushaf_layout/QPC V1 Font.woff2
    - family: Amiri
      fonts:
        - asset: assets/fonts/Amiri-Regular.ttf
        - asset: assets/fonts/Amiri-Bold.ttf
        - asset: assets/fonts/Amiri-Italic.ttf
        - asset: assets/fonts/Amiri-BoldItalic.ttf
    - family: Hafs
      fonts:
        - asset: assets/fonts/HafsNastaleeq.otf
    - family: AmiriQuran
      fonts:
        - asset: assets/quran/fonts/AmiriQuran-Regular.ttf
    - family: Taha
      fonts:
        - asset: assets/quran/fonts/taha.ttf
    - family: me
      fonts:
        - asset: assets/quran/fonts/me_quran.ttf
    - family: qaloon
      fonts:
        - asset: assets/quran/fonts/qaloon.ttf
    - family: pdsm
      fonts:
        - asset: assets/quran/fonts/pdms.otf
    - family: cairo
      fonts:
        - asset: assets/quran/fonts/Cairo-Regular.ttf
        - asset: assets/quran/fonts/Cairo-Bold.ttf
          weight: 700
    - family: "noor ehuda"
      fonts:
        - asset: assets/quran/fonts/noorehuda-org.ttf
    - family: "hafs-nastaleeq-ver10-org"
      fonts:
        - asset: assets/quran/fonts/hafs-nastaleeq-ver10-org.otf
    - family: "jomhuria-regular-full-org"
      fonts:
        - asset: assets/quran/fonts/jomhuria-regular-full-org.ttf
    - family: "mada-regular-full"
      fonts:
        - asset: assets/quran/fonts/mada-regular-full.ttf
    - family: "markazi-text-regular-full-org"
      fonts:
        - asset: assets/quran/fonts/markazi-text-regular-full-org.ttf
    - family: "noto-kufi-arabic-regular-full"
      fonts:
        - asset: assets/quran/fonts/noto-kufi-arabic-regular-full.ttf
    - family: "qumbul-v7-full"
      fonts:
        - asset: assets/quran/fonts/qumbul-v7-full.ttf
    - family: "qur-std"
      fonts:
        - asset: assets/quran/fonts/qur-std.ttf
    - family: "shorooq-full-org"
      fonts:
        - asset: assets/quran/fonts/shorooq-full-org.ttf
    - family: arsura
      fonts:
        - asset: assets/fonts/arsura.ttf
    - family: "KFGQPC Uthmanic Script HAFS Regular"
      fonts:
        - asset: assets/quran/fonts/KFGQPC Uthmanic Script HAFS Regular.otf
    - family: roboto
      fonts:
        - asset: assets/quran/fonts/roboto.ttf
    - family: UthmanicHafs13
      fonts:
        - asset: assets/quran/fonts/UthmanicHafs1 Ver13.otf

    # QCF per-page fonts mapping: QCF_P001 -> QCF2001.ttf, QCF_P002 -> QCF2002.ttf, ...
    # These files are located in: assets/quran/fonts/QCF2BSMLfonts
    # Mapping generated for pages 1..604 (family QCF_P001..QCF_P604)
