name: dartarabic
version: 0.1.2+local
description: Arabic utilities for Dart.
publish_to: "none"

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  string_validator: ^1.0.2

dev_dependencies:
  flutter_lints: ^6.0.0
  test: ^1.24.0
